/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: deploy.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "deploy.pb-c.h"
void   satdeploy__deploy_request__init
                     (Satdeploy__DeployRequest         *message)
{
  static const Satdeploy__DeployRequest init_value = SATDEPLOY__DEPLOY_REQUEST__INIT;
  *message = init_value;
}
size_t satdeploy__deploy_request__get_packed_size
                     (const Satdeploy__DeployRequest *message)
{
  assert(message->base.descriptor == &satdeploy__deploy_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t satdeploy__deploy_request__pack
                     (const Satdeploy__DeployRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &satdeploy__deploy_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t satdeploy__deploy_request__pack_to_buffer
                     (const Satdeploy__DeployRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &satdeploy__deploy_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Satdeploy__DeployRequest *
       satdeploy__deploy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Satdeploy__DeployRequest *)
     protobuf_c_message_unpack (&satdeploy__deploy_request__descriptor,
                                allocator, len, data);
}
void   satdeploy__deploy_request__free_unpacked
                     (Satdeploy__DeployRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &satdeploy__deploy_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   satdeploy__backup_entry__init
                     (Satdeploy__BackupEntry         *message)
{
  static const Satdeploy__BackupEntry init_value = SATDEPLOY__BACKUP_ENTRY__INIT;
  *message = init_value;
}
size_t satdeploy__backup_entry__get_packed_size
                     (const Satdeploy__BackupEntry *message)
{
  assert(message->base.descriptor == &satdeploy__backup_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t satdeploy__backup_entry__pack
                     (const Satdeploy__BackupEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &satdeploy__backup_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t satdeploy__backup_entry__pack_to_buffer
                     (const Satdeploy__BackupEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &satdeploy__backup_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Satdeploy__BackupEntry *
       satdeploy__backup_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Satdeploy__BackupEntry *)
     protobuf_c_message_unpack (&satdeploy__backup_entry__descriptor,
                                allocator, len, data);
}
void   satdeploy__backup_entry__free_unpacked
                     (Satdeploy__BackupEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &satdeploy__backup_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   satdeploy__app_status_entry__init
                     (Satdeploy__AppStatusEntry         *message)
{
  static const Satdeploy__AppStatusEntry init_value = SATDEPLOY__APP_STATUS_ENTRY__INIT;
  *message = init_value;
}
size_t satdeploy__app_status_entry__get_packed_size
                     (const Satdeploy__AppStatusEntry *message)
{
  assert(message->base.descriptor == &satdeploy__app_status_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t satdeploy__app_status_entry__pack
                     (const Satdeploy__AppStatusEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &satdeploy__app_status_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t satdeploy__app_status_entry__pack_to_buffer
                     (const Satdeploy__AppStatusEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &satdeploy__app_status_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Satdeploy__AppStatusEntry *
       satdeploy__app_status_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Satdeploy__AppStatusEntry *)
     protobuf_c_message_unpack (&satdeploy__app_status_entry__descriptor,
                                allocator, len, data);
}
void   satdeploy__app_status_entry__free_unpacked
                     (Satdeploy__AppStatusEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &satdeploy__app_status_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   satdeploy__deploy_response__init
                     (Satdeploy__DeployResponse         *message)
{
  static const Satdeploy__DeployResponse init_value = SATDEPLOY__DEPLOY_RESPONSE__INIT;
  *message = init_value;
}
size_t satdeploy__deploy_response__get_packed_size
                     (const Satdeploy__DeployResponse *message)
{
  assert(message->base.descriptor == &satdeploy__deploy_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t satdeploy__deploy_response__pack
                     (const Satdeploy__DeployResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &satdeploy__deploy_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t satdeploy__deploy_response__pack_to_buffer
                     (const Satdeploy__DeployResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &satdeploy__deploy_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Satdeploy__DeployResponse *
       satdeploy__deploy_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Satdeploy__DeployResponse *)
     protobuf_c_message_unpack (&satdeploy__deploy_response__descriptor,
                                allocator, len, data);
}
void   satdeploy__deploy_response__free_unpacked
                     (Satdeploy__DeployResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &satdeploy__deploy_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor satdeploy__deploy_request__field_descriptors[20] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, command),
    &satdeploy__deploy_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, app_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "param_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, param_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appsys_node",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, appsys_node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "run_node",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, run_node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_path",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, remote_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_server_node",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, dtp_server_node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_server_port",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, dtp_server_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_id",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, payload_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expected_size",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, expected_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expected_checksum",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, expected_checksum),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rollback_hash",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, rollback_hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_seq",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, chunk_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_chunks",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, total_chunks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_data",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, chunk_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_lines",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, log_lines),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_mode",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, file_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_mtu",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, dtp_mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_throughput",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, dtp_throughput),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtp_timeout",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployRequest, dtp_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned satdeploy__deploy_request__field_indices_by_name[] = {
  1,   /* field[1] = app_name */
  3,   /* field[3] = appsys_node */
  14,   /* field[14] = chunk_data */
  12,   /* field[12] = chunk_seq */
  0,   /* field[0] = command */
  17,   /* field[17] = dtp_mtu */
  6,   /* field[6] = dtp_server_node */
  7,   /* field[7] = dtp_server_port */
  18,   /* field[18] = dtp_throughput */
  19,   /* field[19] = dtp_timeout */
  10,   /* field[10] = expected_checksum */
  9,   /* field[9] = expected_size */
  16,   /* field[16] = file_mode */
  15,   /* field[15] = log_lines */
  2,   /* field[2] = param_name */
  8,   /* field[8] = payload_id */
  5,   /* field[5] = remote_path */
  11,   /* field[11] = rollback_hash */
  4,   /* field[4] = run_node */
  13,   /* field[13] = total_chunks */
};
static const ProtobufCIntRange satdeploy__deploy_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor satdeploy__deploy_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "satdeploy.DeployRequest",
  "DeployRequest",
  "Satdeploy__DeployRequest",
  "satdeploy",
  sizeof(Satdeploy__DeployRequest),
  20,
  satdeploy__deploy_request__field_descriptors,
  satdeploy__deploy_request__field_indices_by_name,
  1,  satdeploy__deploy_request__number_ranges,
  (ProtobufCMessageInit) satdeploy__deploy_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor satdeploy__backup_entry__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__BackupEntry, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__BackupEntry, timestamp),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__BackupEntry, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__BackupEntry, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size_bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__BackupEntry, size_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned satdeploy__backup_entry__field_indices_by_name[] = {
  2,   /* field[2] = hash */
  3,   /* field[3] = path */
  4,   /* field[4] = size_bytes */
  1,   /* field[1] = timestamp */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange satdeploy__backup_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor satdeploy__backup_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "satdeploy.BackupEntry",
  "BackupEntry",
  "Satdeploy__BackupEntry",
  "satdeploy",
  sizeof(Satdeploy__BackupEntry),
  5,
  satdeploy__backup_entry__field_descriptors,
  satdeploy__backup_entry__field_indices_by_name,
  1,  satdeploy__backup_entry__number_ranges,
  (ProtobufCMessageInit) satdeploy__backup_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor satdeploy__app_status_entry__field_descriptors[4] =
{
  {
    "app_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__AppStatusEntry, app_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "running",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__AppStatusEntry, running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__AppStatusEntry, file_hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_path",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__AppStatusEntry, remote_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned satdeploy__app_status_entry__field_indices_by_name[] = {
  0,   /* field[0] = app_name */
  2,   /* field[2] = file_hash */
  3,   /* field[3] = remote_path */
  1,   /* field[1] = running */
};
static const ProtobufCIntRange satdeploy__app_status_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor satdeploy__app_status_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "satdeploy.AppStatusEntry",
  "AppStatusEntry",
  "Satdeploy__AppStatusEntry",
  "satdeploy",
  sizeof(Satdeploy__AppStatusEntry),
  4,
  satdeploy__app_status_entry__field_descriptors,
  satdeploy__app_status_entry__field_indices_by_name,
  1,  satdeploy__app_status_entry__number_ranges,
  (ProtobufCMessageInit) satdeploy__app_status_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor satdeploy__deploy_response__field_descriptors[7] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployResponse, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployResponse, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "apps",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Satdeploy__DeployResponse, n_apps),
    offsetof(Satdeploy__DeployResponse, apps),
    &satdeploy__app_status_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backups",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Satdeploy__DeployResponse, n_backups),
    offsetof(Satdeploy__DeployResponse, backups),
    &satdeploy__backup_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_output",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployResponse, log_output),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backup_path",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Satdeploy__DeployResponse, backup_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned satdeploy__deploy_response__field_indices_by_name[] = {
  3,   /* field[3] = apps */
  6,   /* field[6] = backup_path */
  4,   /* field[4] = backups */
  1,   /* field[1] = error_code */
  2,   /* field[2] = error_message */
  5,   /* field[5] = log_output */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange satdeploy__deploy_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor satdeploy__deploy_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "satdeploy.DeployResponse",
  "DeployResponse",
  "Satdeploy__DeployResponse",
  "satdeploy",
  sizeof(Satdeploy__DeployResponse),
  7,
  satdeploy__deploy_response__field_descriptors,
  satdeploy__deploy_response__field_indices_by_name,
  1,  satdeploy__deploy_response__number_ranges,
  (ProtobufCMessageInit) satdeploy__deploy_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue satdeploy__deploy_command__enum_values_by_number[9] =
{
  { "CMD_UNKNOWN", "SATDEPLOY__DEPLOY_COMMAND__CMD_UNKNOWN", 0 },
  { "CMD_STATUS", "SATDEPLOY__DEPLOY_COMMAND__CMD_STATUS", 1 },
  { "CMD_DEPLOY", "SATDEPLOY__DEPLOY_COMMAND__CMD_DEPLOY", 2 },
  { "CMD_ROLLBACK", "SATDEPLOY__DEPLOY_COMMAND__CMD_ROLLBACK", 3 },
  { "CMD_LIST_VERSIONS", "SATDEPLOY__DEPLOY_COMMAND__CMD_LIST_VERSIONS", 4 },
  { "CMD_LOGS", "SATDEPLOY__DEPLOY_COMMAND__CMD_LOGS", 5 },
  { "CMD_UPLOAD_START", "SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_START", 6 },
  { "CMD_UPLOAD_CHUNK", "SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_CHUNK", 7 },
  { "CMD_UPLOAD_END", "SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_END", 8 },
};
static const ProtobufCIntRange satdeploy__deploy_command__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex satdeploy__deploy_command__enum_values_by_name[9] =
{
  { "CMD_DEPLOY", 2 },
  { "CMD_LIST_VERSIONS", 4 },
  { "CMD_LOGS", 5 },
  { "CMD_ROLLBACK", 3 },
  { "CMD_STATUS", 1 },
  { "CMD_UNKNOWN", 0 },
  { "CMD_UPLOAD_CHUNK", 7 },
  { "CMD_UPLOAD_END", 8 },
  { "CMD_UPLOAD_START", 6 },
};
const ProtobufCEnumDescriptor satdeploy__deploy_command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "satdeploy.DeployCommand",
  "DeployCommand",
  "Satdeploy__DeployCommand",
  "satdeploy",
  9,
  satdeploy__deploy_command__enum_values_by_number,
  9,
  satdeploy__deploy_command__enum_values_by_name,
  1,
  satdeploy__deploy_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue satdeploy__deploy_error__enum_values_by_number[16] =
{
  { "ERR_NONE", "SATDEPLOY__DEPLOY_ERROR__ERR_NONE", 0 },
  { "ERR_UNKNOWN_COMMAND", "SATDEPLOY__DEPLOY_ERROR__ERR_UNKNOWN_COMMAND", 1 },
  { "ERR_APP_NOT_FOUND", "SATDEPLOY__DEPLOY_ERROR__ERR_APP_NOT_FOUND", 2 },
  { "ERR_PARAM_SET_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_PARAM_SET_FAILED", 3 },
  { "ERR_BACKUP_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_BACKUP_FAILED", 4 },
  { "ERR_DTP_DOWNLOAD_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_DTP_DOWNLOAD_FAILED", 5 },
  { "ERR_CHECKSUM_MISMATCH", "SATDEPLOY__DEPLOY_ERROR__ERR_CHECKSUM_MISMATCH", 6 },
  { "ERR_INSTALL_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_INSTALL_FAILED", 7 },
  { "ERR_NO_BACKUPS", "SATDEPLOY__DEPLOY_ERROR__ERR_NO_BACKUPS", 8 },
  { "ERR_BACKUP_NOT_FOUND", "SATDEPLOY__DEPLOY_ERROR__ERR_BACKUP_NOT_FOUND", 9 },
  { "ERR_RESTORE_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_RESTORE_FAILED", 10 },
  { "ERR_UPLOAD_IN_PROGRESS", "SATDEPLOY__DEPLOY_ERROR__ERR_UPLOAD_IN_PROGRESS", 11 },
  { "ERR_NO_UPLOAD_IN_PROGRESS", "SATDEPLOY__DEPLOY_ERROR__ERR_NO_UPLOAD_IN_PROGRESS", 12 },
  { "ERR_CHUNK_OUT_OF_ORDER", "SATDEPLOY__DEPLOY_ERROR__ERR_CHUNK_OUT_OF_ORDER", 13 },
  { "ERR_FILE_WRITE_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_FILE_WRITE_FAILED", 14 },
  { "ERR_LOGS_FAILED", "SATDEPLOY__DEPLOY_ERROR__ERR_LOGS_FAILED", 15 },
};
static const ProtobufCIntRange satdeploy__deploy_error__value_ranges[] = {
{0, 0},{0, 16}
};
static const ProtobufCEnumValueIndex satdeploy__deploy_error__enum_values_by_name[16] =
{
  { "ERR_APP_NOT_FOUND", 2 },
  { "ERR_BACKUP_FAILED", 4 },
  { "ERR_BACKUP_NOT_FOUND", 9 },
  { "ERR_CHECKSUM_MISMATCH", 6 },
  { "ERR_CHUNK_OUT_OF_ORDER", 13 },
  { "ERR_DTP_DOWNLOAD_FAILED", 5 },
  { "ERR_FILE_WRITE_FAILED", 14 },
  { "ERR_INSTALL_FAILED", 7 },
  { "ERR_LOGS_FAILED", 15 },
  { "ERR_NONE", 0 },
  { "ERR_NO_BACKUPS", 8 },
  { "ERR_NO_UPLOAD_IN_PROGRESS", 12 },
  { "ERR_PARAM_SET_FAILED", 3 },
  { "ERR_RESTORE_FAILED", 10 },
  { "ERR_UNKNOWN_COMMAND", 1 },
  { "ERR_UPLOAD_IN_PROGRESS", 11 },
};
const ProtobufCEnumDescriptor satdeploy__deploy_error__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "satdeploy.DeployError",
  "DeployError",
  "Satdeploy__DeployError",
  "satdeploy",
  16,
  satdeploy__deploy_error__enum_values_by_number,
  16,
  satdeploy__deploy_error__enum_values_by_name,
  1,
  satdeploy__deploy_error__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
