/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: deploy.proto */

#ifndef PROTOBUF_C_deploy_2eproto__INCLUDED
#define PROTOBUF_C_deploy_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Satdeploy__DeployRequest Satdeploy__DeployRequest;
typedef struct Satdeploy__BackupEntry Satdeploy__BackupEntry;
typedef struct Satdeploy__AppStatusEntry Satdeploy__AppStatusEntry;
typedef struct Satdeploy__DeployResponse Satdeploy__DeployResponse;


/* --- enums --- */

/*
 * Command types for the deploy protocol
 */
typedef enum _Satdeploy__DeployCommand {
  SATDEPLOY__DEPLOY_COMMAND__CMD_UNKNOWN = 0,
  /*
   * Query agent status, list deployed apps
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_STATUS = 1,
  /*
   * (Legacy) Deploy via DTP download
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_DEPLOY = 2,
  /*
   * Restore previous version
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_ROLLBACK = 3,
  /*
   * List available backups for an app
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_LIST_VERSIONS = 4,
  /*
   * Fetch service logs from target
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_LOGS = 5,
  /*
   * Start direct file upload (sends metadata)
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_START = 6,
  /*
   * File data chunk
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_CHUNK = 7,
  /*
   * End upload and trigger install
   */
  SATDEPLOY__DEPLOY_COMMAND__CMD_UPLOAD_END = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SATDEPLOY__DEPLOY_COMMAND)
} Satdeploy__DeployCommand;
/*
 * Error codes
 */
typedef enum _Satdeploy__DeployError {
  SATDEPLOY__DEPLOY_ERROR__ERR_NONE = 0,
  SATDEPLOY__DEPLOY_ERROR__ERR_UNKNOWN_COMMAND = 1,
  SATDEPLOY__DEPLOY_ERROR__ERR_APP_NOT_FOUND = 2,
  SATDEPLOY__DEPLOY_ERROR__ERR_PARAM_SET_FAILED = 3,
  SATDEPLOY__DEPLOY_ERROR__ERR_BACKUP_FAILED = 4,
  SATDEPLOY__DEPLOY_ERROR__ERR_DTP_DOWNLOAD_FAILED = 5,
  SATDEPLOY__DEPLOY_ERROR__ERR_CHECKSUM_MISMATCH = 6,
  SATDEPLOY__DEPLOY_ERROR__ERR_INSTALL_FAILED = 7,
  SATDEPLOY__DEPLOY_ERROR__ERR_NO_BACKUPS = 8,
  SATDEPLOY__DEPLOY_ERROR__ERR_BACKUP_NOT_FOUND = 9,
  SATDEPLOY__DEPLOY_ERROR__ERR_RESTORE_FAILED = 10,
  SATDEPLOY__DEPLOY_ERROR__ERR_UPLOAD_IN_PROGRESS = 11,
  SATDEPLOY__DEPLOY_ERROR__ERR_NO_UPLOAD_IN_PROGRESS = 12,
  SATDEPLOY__DEPLOY_ERROR__ERR_CHUNK_OUT_OF_ORDER = 13,
  SATDEPLOY__DEPLOY_ERROR__ERR_FILE_WRITE_FAILED = 14,
  SATDEPLOY__DEPLOY_ERROR__ERR_LOGS_FAILED = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SATDEPLOY__DEPLOY_ERROR)
} Satdeploy__DeployError;

/* --- messages --- */

/*
 * Request message sent from ground to satellite
 */
struct  Satdeploy__DeployRequest
{
  ProtobufCMessage base;
  Satdeploy__DeployCommand command;
  /*
   * App identification
   */
  char *app_name;
  /*
   * e.g., "mng_dipp"
   */
  char *param_name;
  /*
   * CSP node addresses
   */
  /*
   * a53-app-sys-manager node (e.g., 5421)
   */
  uint32_t appsys_node;
  /*
   * Node where app runs (e.g., 5423 for DIPP)
   */
  uint32_t run_node;
  /*
   * File paths
   */
  /*
   * Installation path on satellite (e.g., /usr/bin/dipp)
   */
  char *remote_path;
  /*
   * DTP transfer parameters
   */
  /*
   * Ground station CSP node address
   */
  uint32_t dtp_server_node;
  /*
   * DTP server port (typically 7)
   */
  uint32_t dtp_server_port;
  /*
   * DTP payload identifier
   */
  uint32_t payload_id;
  /*
   * Expected file size in bytes
   */
  uint32_t expected_size;
  /*
   * Expected full 64-hex SHA256 checksum (gates resume on agent)
   */
  char *expected_checksum;
  /*
   * For rollback command
   */
  /*
   * Specific backup hash to restore (optional)
   */
  char *rollback_hash;
  /*
   * For direct upload (CMD_UPLOAD_START, CMD_UPLOAD_CHUNK, CMD_UPLOAD_END)
   */
  /*
   * Chunk sequence number (0-based)
   */
  uint32_t chunk_seq;
  /*
   * Total number of chunks
   */
  uint32_t total_chunks;
  /*
   * File data chunk (max ~1500 bytes per chunk)
   */
  ProtobufCBinaryData chunk_data;
  /*
   * For CMD_LOGS
   */
  /*
   * Number of log lines to fetch (default: 100)
   */
  uint32_t log_lines;
  /*
   * Source file permission mode (e.g., 0755, 0644). 0 = use default (0755).
   */
  uint32_t file_mode;
  /*
   * DTP transfer tuning (0 = use agent defaults)
   */
  /*
   * Max transmission unit in bytes (default: 1024)
   */
  uint32_t dtp_mtu;
  /*
   * Target throughput in bytes/s (default: 10000000)
   */
  uint32_t dtp_throughput;
  /*
   * Transfer timeout in seconds (default: 60)
   */
  uint32_t dtp_timeout;
};
#define SATDEPLOY__DEPLOY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&satdeploy__deploy_request__descriptor) \
    , SATDEPLOY__DEPLOY_COMMAND__CMD_UNKNOWN, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, {0,NULL}, 0, 0, 0, 0, 0 }


/*
 * Backup information returned by CMD_LIST_VERSIONS
 */
struct  Satdeploy__BackupEntry
{
  ProtobufCMessage base;
  /*
   * Version string (e.g., "20250115-143022-a1b2c3d4")
   */
  char *version;
  /*
   * Human-readable timestamp
   */
  char *timestamp;
  /*
   * File hash
   */
  char *hash;
  /*
   * Full path on target — deploy slot for "current",
   */
  char *path;
  /*
   * backup .bak file for archives.
   */
  /*
   * File size in bytes (0 = unknown / older agent
   */
  uint64_t size_bytes;
};
#define SATDEPLOY__BACKUP_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&satdeploy__backup_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * App status information returned by CMD_STATUS
 */
struct  Satdeploy__AppStatusEntry
{
  ProtobufCMessage base;
  char *app_name;
  protobuf_c_boolean running;
  char *file_hash;
  char *remote_path;
};
#define SATDEPLOY__APP_STATUS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&satdeploy__app_status_entry__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Response message sent from satellite to ground
 */
struct  Satdeploy__DeployResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  uint32_t error_code;
  char *error_message;
  /*
   * For CMD_STATUS
   */
  size_t n_apps;
  Satdeploy__AppStatusEntry **apps;
  /*
   * For CMD_LIST_VERSIONS
   */
  size_t n_backups;
  Satdeploy__BackupEntry **backups;
  /*
   * For CMD_LOGS
   */
  char *log_output;
  /*
   * For CMD_DEPLOY
   */
  char *backup_path;
};
#define SATDEPLOY__DEPLOY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&satdeploy__deploy_response__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Satdeploy__DeployRequest methods */
void   satdeploy__deploy_request__init
                     (Satdeploy__DeployRequest         *message);
size_t satdeploy__deploy_request__get_packed_size
                     (const Satdeploy__DeployRequest   *message);
size_t satdeploy__deploy_request__pack
                     (const Satdeploy__DeployRequest   *message,
                      uint8_t             *out);
size_t satdeploy__deploy_request__pack_to_buffer
                     (const Satdeploy__DeployRequest   *message,
                      ProtobufCBuffer     *buffer);
Satdeploy__DeployRequest *
       satdeploy__deploy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   satdeploy__deploy_request__free_unpacked
                     (Satdeploy__DeployRequest *message,
                      ProtobufCAllocator *allocator);
/* Satdeploy__BackupEntry methods */
void   satdeploy__backup_entry__init
                     (Satdeploy__BackupEntry         *message);
size_t satdeploy__backup_entry__get_packed_size
                     (const Satdeploy__BackupEntry   *message);
size_t satdeploy__backup_entry__pack
                     (const Satdeploy__BackupEntry   *message,
                      uint8_t             *out);
size_t satdeploy__backup_entry__pack_to_buffer
                     (const Satdeploy__BackupEntry   *message,
                      ProtobufCBuffer     *buffer);
Satdeploy__BackupEntry *
       satdeploy__backup_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   satdeploy__backup_entry__free_unpacked
                     (Satdeploy__BackupEntry *message,
                      ProtobufCAllocator *allocator);
/* Satdeploy__AppStatusEntry methods */
void   satdeploy__app_status_entry__init
                     (Satdeploy__AppStatusEntry         *message);
size_t satdeploy__app_status_entry__get_packed_size
                     (const Satdeploy__AppStatusEntry   *message);
size_t satdeploy__app_status_entry__pack
                     (const Satdeploy__AppStatusEntry   *message,
                      uint8_t             *out);
size_t satdeploy__app_status_entry__pack_to_buffer
                     (const Satdeploy__AppStatusEntry   *message,
                      ProtobufCBuffer     *buffer);
Satdeploy__AppStatusEntry *
       satdeploy__app_status_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   satdeploy__app_status_entry__free_unpacked
                     (Satdeploy__AppStatusEntry *message,
                      ProtobufCAllocator *allocator);
/* Satdeploy__DeployResponse methods */
void   satdeploy__deploy_response__init
                     (Satdeploy__DeployResponse         *message);
size_t satdeploy__deploy_response__get_packed_size
                     (const Satdeploy__DeployResponse   *message);
size_t satdeploy__deploy_response__pack
                     (const Satdeploy__DeployResponse   *message,
                      uint8_t             *out);
size_t satdeploy__deploy_response__pack_to_buffer
                     (const Satdeploy__DeployResponse   *message,
                      ProtobufCBuffer     *buffer);
Satdeploy__DeployResponse *
       satdeploy__deploy_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   satdeploy__deploy_response__free_unpacked
                     (Satdeploy__DeployResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Satdeploy__DeployRequest_Closure)
                 (const Satdeploy__DeployRequest *message,
                  void *closure_data);
typedef void (*Satdeploy__BackupEntry_Closure)
                 (const Satdeploy__BackupEntry *message,
                  void *closure_data);
typedef void (*Satdeploy__AppStatusEntry_Closure)
                 (const Satdeploy__AppStatusEntry *message,
                  void *closure_data);
typedef void (*Satdeploy__DeployResponse_Closure)
                 (const Satdeploy__DeployResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    satdeploy__deploy_command__descriptor;
extern const ProtobufCEnumDescriptor    satdeploy__deploy_error__descriptor;
extern const ProtobufCMessageDescriptor satdeploy__deploy_request__descriptor;
extern const ProtobufCMessageDescriptor satdeploy__backup_entry__descriptor;
extern const ProtobufCMessageDescriptor satdeploy__app_status_entry__descriptor;
extern const ProtobufCMessageDescriptor satdeploy__deploy_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_deploy_2eproto__INCLUDED */
